defaults:
  - train_config
  - override hydra/launcher: slurm
  - _self_

main_config:
  _target_: "cluster_train.main"
  # _target_: "__main__.main"
  env_name: "HalfCheetahV2"
  seed: 42
  num_epochs: 500
  num_train_tasks: 25
  num_test_tasks: 25
  encoder_hidden_size: 200
  net_size: 300
  num_steps_per_epoch: 2000
  num_initial_steps: 2000
  num_steps_prior: 400
  num_extra_rl_steps_posterior: 600
  batch_size: 256
  embedding_batch_size: 100
  embedding_mini_batch_size: 100
  max_episode_length: 1000

wandb_group: ${main_config.env_name}
wandb_project_name: "adaptive-context-rl"
use_wandb: True
wandb_run_name: PEARL-seed=${main_config.seed}-${now:%Y-%m-%d_%H-%M-%S}
wandb_tags:
  - "PEARL"
  - ${main_config.env_name}

hydra:
  run:
    dir: output/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true
  sweep:
    dir: ${hydra.run.dir}
    subdir: ${hydra.job.num}
  job_logging:
    root:
      level: INFO # DEBUG
